### ISSUE TITLE
Can't compile on arm64 with OTP 21.1

### ISSUE THREAD

**Issue by masual** [emqx/emqx-rel#250]
I managed to compile and install Erlang 21.1 on Armbian running on an H6 SoC (arm64). 
Following the steps to compile emqx, I get the following error:

> cloning into 'neotoma'...
==> getopt (get-deps)
==> neotoma (get-deps)
./rebar compile
==> getopt (compile)
=ERROR REPORT==== 13-Nov-2018::23:59:19.277357 ===
beam/beam_load.c(1878): Error loading module compile:
  This BEAM file was compiled for a later version of the run-time system than 21.
  To fix this, please recompile this module with an 21 compiler.
  (Use of opcode 164; this emulator supports only up to 163.)
=ERROR REPORT==== 13-Nov-2018::23:59:19.277391 ===
Loading of /usr/local/lib/erlang/lib/compiler-7.2.6/ebin/compile.beam failed: badfile
unexpected error compiling src/getopt.erl
{'EXIT',{undef,[{compile,file,
                         ["src/getopt.erl",
                          [{outdir,"ebin"},
                           debug_info,warn_unused_vars,warn_export_all,
                           warn_shadow_vars,warn_unused_import,
                           warn_unused_function,warn_bif_clash,
                           warn_unused_record,warn_deprecated_function,
                           warn_obsolete_guard,strict_validation,
                           warn_export_vars,warn_exported_vars,
                           warn_missing_spec,warn_untyped_record,debug_info,
                           {i,"include"},
                           return]],
                         []},
                {rebar_erlc_compiler,internal_erl_compile,4,[]},
                {rebar_base_compiler,compile,3,[]},
                {rebar_base_compiler,compile_worker,3,[]}]}}
ERROR: compile failed while processing /home/masual/emq/emqx-rel/deps/getopt: rebar_abort
Makefile:17: recipe for target 'compile' failed
make[2]: *** [compile] Error 1
make[2]: Leaving directory '/home/masual/emq/emqx-rel/deps/cuttlefish'
../../erlang.mk:312: recipe for target 'deps' failed
make[1]: *** [deps] Error 2
make[1]: Leaving directory '/home/masual/emq/emqx-rel/deps/emqx'
erlang.mk:310: recipe for target 'deps' failed
make: *** [deps] Error 2

For the error I understand that some modules are built to be compiled with Erlang OTP 22. I also tryed installing OTP 22 but the Makefile checks that the version should be 21 and stops the compilation too.
 
The output of erl is:

> $ erl
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]
Eshell V10.1  (abort with ^G)
1>

Any help will be appreciated.

**Comment by Gilbert-Wong** [comment]
I encountered the same issue few months ago, the erlang environment is not fully installed on your machine. The final version of Erlang OTP 22 has not been released now. So emqx-rel has no modules which require OTP 22 to compile.

**Comment by masual** [comment]
Thank you for your feedback. How did you managed to fully install Erlang OTP 21, and which is the exact Erlang release you installed? Regards.

**Comment by Gilbert-Wong** [comment]
For example, if you use raspberry with raspbian, you can try with https://www.erlang-solutions.com/

**Comment by eternasparta** [comment]
I've used this tutorial to install ergland and I'm able to compile emq on my RPI 3b+ running raspbian: 

https://elinux.org/Erlang

maybe it helps.
